name: Release

on:
    push:
        tags:
            - 'v*'
permissions:
    contents: write
    packages: write
    id-token: write

jobs:
    build-chainlaunch-ui:
        name: Build Chainlaunch UI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
            - name: Build chainlaunch-ui
              run: |
                  cd web
                  bun install
                  export API_URL="/api"
                  bun run build
            - name: Upload chainlaunch-ui artifact
              uses: actions/upload-artifact@v4
              with:
                  name: chainlaunch-ui-dist
                  path: web/dist

    build-linux:
        name: Build Linux Binaries
        runs-on: ubuntu-latest
        needs: build-chainlaunch-ui
        strategy:
            matrix:
                arch: [amd64]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Download chainlaunch-ui artifact
              uses: actions/download-artifact@v4
              with:
                  name: chainlaunch-ui-dist
                  path: web/dist

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.23.4'
                  cache-dependency-path: 'go.sum'

            - name: Download Go modules
              run: go mod download

            - name: Build Linux binary
              run: |
                CGO_ENABLED=1 GOOS=linux GOARCH=${{ matrix.arch }} go build -ldflags="-X 'github.com/chainlaunch/chainlaunch/pkg/version.Version=${{ github.ref_name }}' -X 'github.com/chainlaunch/chainlaunch/pkg/version.GitCommit=${{ github.sha }}' -X 'github.com/chainlaunch/chainlaunch/pkg/version.BuildTime=$(date -u +'%Y-%m-%dT%H:%M:%SZ')'" -o chainlaunch-linux-${{ matrix.arch }} main.go

            - name: Create zip archive
              run: |
                zip chainlaunch-linux-${{ matrix.arch }}.zip chainlaunch-linux-${{ matrix.arch }}

            - name: Upload Linux binary and zip as artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: chainlaunch-linux-${{ matrix.arch }}
                  path: |
                    ./chainlaunch-linux-${{ matrix.arch }}
                    ./chainlaunch-linux-${{ matrix.arch }}.zip

    build-darwin:
        name: Build Darwin Binaries
        runs-on: macos-latest
        needs: build-chainlaunch-ui
        strategy:
            matrix:
                arch: [amd64, arm64]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Download chainlaunch-ui artifact
              uses: actions/download-artifact@v4
              with:
                  name: chainlaunch-ui-dist
                  path: web/dist

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.23.4'
                  cache-dependency-path: 'go.sum'

            - name: Download Go modules
              run: go mod download

            - name: Build Darwin binary
              run: |
                CGO_ENABLED=1 GOOS=darwin GOARCH=${{ matrix.arch }} go build -ldflags="-X 'github.com/chainlaunch/chainlaunch/pkg/version.Version=${{ github.ref_name }}' -X 'github.com/chainlaunch/chainlaunch/pkg/version.GitCommit=${{ github.sha }}' -X 'github.com/chainlaunch/chainlaunch/pkg/version.BuildTime=$(date -u +'%Y-%m-%dT%H:%M:%SZ')'" -o chainlaunch-darwin-${{ matrix.arch }} main.go

            - name: Create zip archive
              run: |
                zip chainlaunch-darwin-${{ matrix.arch }}.zip chainlaunch-darwin-${{ matrix.arch }}

            - name: Upload Darwin binary and zip as artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: chainlaunch-darwin-${{ matrix.arch }}
                  path: |
                    ./chainlaunch-darwin-${{ matrix.arch }}
                    ./chainlaunch-darwin-${{ matrix.arch }}.zip

    create-release:
        name: Create Release
        needs: [build-linux, build-darwin]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: ./artifacts

            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref_name }}
                  name: ${{ github.ref_name }}
                  draft: false
                  prerelease: false
                  files: |
                    ./artifacts/chainlaunch-linux-amd64/chainlaunch-linux-amd64.zip
                    ./artifacts/chainlaunch-darwin-amd64/chainlaunch-darwin-amd64.zip
                    ./artifacts/chainlaunch-darwin-arm64/chainlaunch-darwin-arm64.zip


